# Generated by Django 4.1.2 on 2022-10-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_left', models.IntegerField(default=1)),
                ('value_right', models.IntegerField(default=1)),
                ('currency_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_left', to='exchanger.currency')),
                ('currency_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_right', to='exchanger.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rates',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
    ]
