# Generated by Django 4.1.2 on 2022-10-29 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_icon', models.ImageField(max_length=255, null=True, upload_to='currency_images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('price_dollars', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('price_dollars',),
            },
        ),
        migrations.CreateModel(
            name='ProfitTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usdt', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('total_usdt',),
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_exchange', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_received', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirm', models.BooleanField(default=False)),
                ('reference_dollars', models.DecimalField(blank=True, decimal_places=30, max_digits=60, null=True)),
                ('currency_exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_exchange', to='exchanger.currency')),
                ('currency_received', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_received', to='exchanger.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transaction',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_left', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('value_right', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_value', models.DecimalField(decimal_places=30, default=10000.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.DecimalField(decimal_places=30, default=10000.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_commission', models.DecimalField(decimal_places=4, default=0.005, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('blockchain_commission', models.DecimalField(decimal_places=4, default=0.001, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_left', to='exchanger.currency')),
                ('currency_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_right', to='exchanger.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rates',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
    ]
