# Generated by Django 4.1.2 on 2022-10-08 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_alter_exchangerates_value_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='value_left',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='value_right',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
