# Generated by Django 4.1.2 on 2022-10-09 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanger', '0004_alter_exchangerates_value_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_exchange', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_received', models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency_exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_exchange', to='exchanger.currency')),
                ('currency_received', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_received', to='exchanger.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transaction',
                'ordering': ['created_at'],
            },
        ),
    ]
