# Generated by Django 4.1.2 on 2022-10-31 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0005_add_level_profit_dedault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='max_value',
            field=models.DecimalField(decimal_places=30, default=100000.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='min_value',
            field=models.DecimalField(decimal_places=30, default=1000.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
