# Generated by Django 4.1.2 on 2022-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0005_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='reference_dollars',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=60, null=True),
        ),
    ]
