# Generated by Django 4.1.2 on 2022-11-06 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0006_alter_exchangerates_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_from_white_bit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('payment_expected', 'payment_expected'), ('payment_received', 'payment_received'), ('currency_changing', 'currency_changing'), ('create_for_payment', 'create_for_payment'), ('complete', 'complete')], default='payment_expected', max_length=30),
        ),
        migrations.AddField(
            model_name='transactions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
