# Generated by Django 4.1.2 on 2022-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0006_transactions_is_confirm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('price_dollars', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('price_dollars',),
            },
        ),
        migrations.CreateModel(
            name='ProfitTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usdt', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('total_usdt',),
            },
        ),
    ]
