# Generated by Django 4.1.2 on 2022-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0007_currency_name_from_white_bit_currency_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='fiat',
            field=models.BooleanField(default=False),
        ),
    ]
