# Generated by Django 4.1.2 on 2022-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0009_remove_exchangerates_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='network_for_min_max',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
