# Generated by Django 4.1.2 on 2022-11-08 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0010_currency_network_for_min_max'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['created_at', 'is_confirm'], 'verbose_name': 'Transactions', 'verbose_name_plural': 'Transaction'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status_time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('payment_received', 'payment_received'), ('currency_changing', 'currency_changing'), ('create_for_payment', 'create_for_payment'), ('completed', 'completed')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
