# Generated by Django 4.1.2 on 2022-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0010_add_profit_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='image_icon',
            field=models.ImageField(max_length=255, null=True, upload_to='currency_images/%Y/%m/%d/'),
        ),
    ]
