# Generated by Django 4.1.2 on 2022-10-29 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0011_currency_image_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerates',
            name='blockchain_commission',
            field=models.DecimalField(decimal_places=4, default=0.001, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='max_value',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='min_value',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='service_commission',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
