# Generated by Django 4.1.2 on 2022-11-08 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0011_alter_transactions_options_transactions_failed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
