# Generated by Django 4.1.2 on 2022-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0012_alter_transactions_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
