# Generated by Django 4.1.2 on 2022-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0013_transactions_email_alter_transactions_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
