# Generated by Django 4.1.2 on 2022-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0014_transactions_deposit_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-created_at', 'is_confirm'], 'verbose_name': 'Transactions', 'verbose_name_plural': 'Transaction'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='failed_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('payment_received', 'payment_received'), ('currency_changing', 'currency_changing'), ('create_for_payment', 'create_for_payment'), ('withdraw_pending', 'withdraw_pending'), ('completed', 'completed')], default='created', max_length=30),
        ),
    ]
