# Generated by Django 4.1.2 on 2022-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0015_alter_transactions_options_transactions_failed_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='try_fixed_count_error',
            field=models.IntegerField(default=0),
        ),
    ]
