# Generated by Django 4.1.2 on 2022-11-09 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0016_transactions_try_fixed_count_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='commission_deposit',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='currency',
            name='commission_withdraw',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
