# Generated by Django 4.1.2 on 2022-11-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0017_currency_commission_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_bit_commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('service_commission', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
