# Generated by Django 4.1.2 on 2022-11-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0019_add_default_commisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='blockchain_commission',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='service_commission',
        ),
    ]
