# Generated by Django 4.1.2 on 2022-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0020_remove_exchangerates_blockchain_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissions',
            name='service_commission',
        ),
        migrations.AddField(
            model_name='commissions',
            name='service_commission_to_crypto',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='commissions',
            name='service_commission_to_fiat',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='white_bit_commission',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
        ),
    ]
