# Generated by Django 4.1.2 on 2022-11-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0021_remove_commissions_service_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
