# Generated by Django 4.1.2 on 2022-11-11 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0022_transactions_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='fiat_unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
