# Generated by Django 4.1.2 on 2022-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0023_transactions_fiat_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
