# Generated by Django 4.1.2 on 2022-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0024_currency_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='address_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='address_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
