# Generated by Django 4.1.2 on 2022-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0025_transactions_address_from_transactions_address_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status_exchange',
            field=models.CharField(choices=[('created', 'created'), ('transfer_to_trade', 'transfer_to_trade'), ('exchange', 'exchange'), ('transfer_to_main', 'transfer_to_main'), ('create_withdraw', 'create_withdraw')], default='created', max_length=100),
        ),
    ]
