# Generated by Django 4.1.2 on 2022-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0026_transactions_status_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='get_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
