# Generated by Django 4.1.2 on 2022-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0027_transactions_get_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='fail_pending',
            field=models.BooleanField(default=False),
        ),
    ]
