# Generated by Django 4.1.2 on 2022-11-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0029_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-fail_pending', '-created_at', 'is_confirm'], 'verbose_name': 'Transactions', 'verbose_name_plural': 'Transaction'},
        ),
    ]
