# Generated by Django 4.1.2 on 2022-12-16 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanger', '0030_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissions',
            options={'verbose_name_plural': 'Комиссия'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюты', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'verbose_name': 'Курсы валют', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='profitmodel',
            options={'ordering': ('price_dollars',), 'verbose_name_plural': 'Кэшбек за рефералов'},
        ),
        migrations.AlterModelOptions(
            name='profittotal',
            options={'ordering': ('total_usdt',), 'verbose_name': 'Прибыль сайта', 'verbose_name_plural': 'Прибыль сайта'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-fail_pending', '-created_at', 'is_confirm'], 'verbose_name': 'Транзакции', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='commission_withdraw',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='service_commission_to_crypto',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Комиссия на вывод CRYPTO'),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='service_commission_to_fiat',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Комиссия на вывод FIAT'),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='white_bit_commission',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4, verbose_name='Процент комиссии White Bit'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название на сайте'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='currency_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_left', to='exchanger.currency', verbose_name='Валюта слева'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='currency_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_right', to='exchanger.currency', verbose_name='Валюта справа'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='value_left',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Валюта слева значение'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='value_right',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Валюта справа значение'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='price_dollars',
            field=models.IntegerField(verbose_name='Эквивалент в USDT'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент кэшбека'),
        ),
        migrations.AlterField(
            model_name='profittotal',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент прибыли'),
        ),
        migrations.AlterField(
            model_name='profittotal',
            name='total_usdt',
            field=models.IntegerField(verbose_name='Эквивалент в USDT'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_exchange',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумму отдаю'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_received',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумму получаю'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_exchange', to='exchanger.currency', verbose_name='Валюту отдаю'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_received', to='exchanger.currency', verbose_name='Валюту получаю'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='fail_pending',
            field=models.BooleanField(default=False, verbose_name='Ошибка обменника (отправка)'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Ошибка обменника'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='get_deposit',
            field=models.BooleanField(default=False, verbose_name='Зачислено на White Bit'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Проведено'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reference_dollars',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=60, null=True, verbose_name='"Эквивалент в USDT'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status_time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление статуса'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='try_fixed_count_error',
            field=models.IntegerField(default=0, verbose_name='Количество попыток устранить ошибку'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
