# Generated by Django 4.1.2 on 2022-11-02 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_from_referral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
