# Generated by Django 4.1.2 on 2022-10-07 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 16, 17, 47, 539506)),
        ),
    ]
