# Generated by Django 4.1.2 on 2022-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_paid_from_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
