# Generated by Django 4.1.2 on 2022-11-12 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_two_factor_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cents',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_info_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usdt', models.DecimalField(decimal_places=5, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_confirm', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
