# Generated by Django 4.1.2 on 2022-11-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_payouts_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payouts',
            options={'ordering': ('-created_at', 'price_usdt')},
        ),
    ]
