# Generated by Django 4.1.2 on 2022-12-16 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='payouts',
            options={'ordering': ('-created_at', 'price_usdt'), 'verbose_name_plural': 'Запрос на вывод средств'},
        ),
        migrations.AlterModelOptions(
            name='referralrelationship',
            options={'verbose_name_plural': 'Отношение пользователей'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее действие на сайте'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='paid_from_referral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень рефералов'),
        ),
        migrations.AlterField(
            model_name='referralrelationship',
            name='invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Реферал'),
        ),
        migrations.AlterField(
            model_name='referralrelationship',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='Рефер'),
        ),
    ]
