# Generated by Django 4.1.2 on 2022-10-07 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_last_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrelationship',
            name='refer_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='inviter_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 19, 3, 32, 448272)),
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
