# Generated by Django 4.1.2 on 2022-10-08 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_referralrelationship_refer_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 10, 5, 17, 251843)),
        ),
    ]
