# Generated by Django 4.1.2 on 2022-10-08 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 10, 7, 50, 901377)),
        ),
    ]
