# Generated by Django 4.1.2 on 2022-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customuser_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
