# Generated by Django 4.1.2 on 2022-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customuser_reset_password_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_dollars', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('price_dollars',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], null=True),
        ),
    ]
