# Generated by Django 4.1.2 on 2022-10-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profitmodel_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitmodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
