# Generated by Django 4.1.2 on 2022-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_profitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, null=True),
        ),
    ]
