# Generated by Django 4.1.2 on 2022-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=90)),
                ('answer', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Faq settings',
                'verbose_name_plural': 'Faq settings',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_image', models.ImageField(null=True, upload_to='logo_images/')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
