# Generated by Django 4.1.2 on 2022-10-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='actions_images/')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Action',
            },
        ),
    ]
