# Generated by Django 4.1.2 on 2022-11-01 20:43

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(null=True, upload_to='logo_images/')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'FeedbackSites',
                'verbose_name_plural': 'FeedbackSites',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackMonitoring',
        ),
        migrations.RenameModel(
            old_name='FeedbackTranslation',
            new_name='FeedbackMonitoringTranslation',
        ),
        migrations.AlterModelOptions(
            name='feedbackmonitoring',
            options={'verbose_name': 'FeedbackMonitoring', 'verbose_name_plural': 'FeedbackMonitoring'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmonitoringtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'FeedbackMonitoring Translation'},
        ),
        migrations.AlterModelTable(
            name='feedbackmonitoringtranslation',
            table='important_info_feedbackmonitoring_translation',
        ),
        migrations.CreateModel(
            name='FeedbackSitesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='important_info.feedbacksites')),
            ],
            options={
                'verbose_name': 'FeedbackSites Translation',
                'db_table': 'important_info_feedbacksites_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
