# Generated by Django 4.1.2 on 2022-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0002_feedbacksites_rename_feedback_feedbackmonitoring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1024)),
                ('telegram', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GetInTouch',
                'verbose_name_plural': 'GetInTouch',
            },
        ),
    ]
