# Generated by Django 4.1.2 on 2022-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0003_getintouchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchmodel',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
