# Generated by Django 4.1.2 on 2022-11-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0004_alter_getintouchmodel_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getintouchmodel',
            options={'ordering': ['-created_at', 'viewed'], 'verbose_name': 'GetInTouch', 'verbose_name_plural': 'GetInTouch'},
        ),
    ]
