# Generated by Django 4.1.2 on 2022-12-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_info', '0005_alter_getintouchmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='actiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Акции Translation'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ настройки', 'verbose_name_plural': 'FAQ настройки'},
        ),
        migrations.AlterModelOptions(
            name='faqtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'FAQ настройки Translation'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmonitoring',
            options={'verbose_name': 'Отзывы Monitoring', 'verbose_name_plural': 'Отзывы FeedbackMonitoring'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmonitoringtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Отзывы Monitoring Translation'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksites',
            options={'verbose_name': 'Отзывы сайтов', 'verbose_name_plural': 'Отзывы сайтов'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksitestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Отзывы сайтов Translation'},
        ),
        migrations.AlterModelOptions(
            name='getintouchmodel',
            options={'ordering': ['-created_at', 'viewed'], 'verbose_name': 'Связаться с нами (уведомления от юзеров)', 'verbose_name_plural': 'Связаться с нами (уведомления от юзеров)'},
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedbackmonitoring',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='feedbackmonitoring',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='feedbacksites',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='feedbacksites',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='logo_images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='getintouchmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='getintouchmodel',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
