# Generated by Django 4.1.2 on 2022-12-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_default_analytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsexchange',
            options={'verbose_name': 'Аналитика', 'verbose_name_plural': 'Аналитика'},
        ),
        migrations.AlterField(
            model_name='analyticsexchange',
            name='name',
            field=models.CharField(default='analytics', max_length=100, verbose_name='Аналитика'),
        ),
    ]
