# Generated by Django 4.1.2 on 2022-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='post',
            name='recommendation',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_recommendation', to='blog.post'),
        ),
    ]
