# Generated by Django 4.1.2 on 2022-12-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_recommendation_post_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created'], 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Категории (тэги)'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='minutes_for_reading',
            field=models.IntegerField(default=1, verbose_name='Минут для чтения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recommendation',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_recommendation', to='blog.post', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.tag', verbose_name='Категория (тэг)'),
        ),
    ]
