# Generated by Django 4.1.2 on 2022-10-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='minutes_for_reading',
            field=models.IntegerField(default=1),
        ),
    ]
